# Site settings
author: Mark Drehmann
title: Mark's Coding Story
header-img: img/home-bg.png
email: markdrehmann@gmail.com
copyright_name: Mark Drehmann
description: > # this means to ignore newlines until "baseurl:"
  Code like you mean it.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  markdrehmann

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
